server:
  port: 8060


# ===================================================================
# \u5206\u5E03\u5F0F\u6587\u4EF6\u7CFB\u7EDFFDFS\u914D\u7F6E
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 6000
  thumb-image:             #\u7F29\u7565\u56FE\u751F\u6210\u53C2\u6570
    width: 150
    height: 150
  web-server-url: 192.168.130.130/
  tracker-list:
    - 192.168.130.130:22122     #\u5982\u679C\u6709\u591A\u4E2Atracker\u8282\u70B9\u53EF\u4EE5\u6DFB\u52A0\u591A\u884C
